### ISSUE TITLE
clean up deps

### ISSUE THREAD

**Issue by transitive-bullshit** [lmnr-ai/lmnr-ts#1]
I'm guessing these extremely heavy deps are meant to be dev deps:

https://github.com/lmnr-ai/lmnr-ts/blob/a45f7ace04d5ab3f7448f77f31c8205dbb321a4a/package.json#L29-L31

**Comment by dinmukhamedm** [comment]
Yes true, good catch, thanks for opening the first issue. We'll fix this with the next release
